### ISSUE TITLE
Add Vue.js questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#105]
Add questions and answers that might test core Vue concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Fill in here under 'Vue' deck ](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) and submit pull request.

[Example of question types / length](https://github.com/khan4019/front-end-Interview-Questions#html-basic-questions-for-begginers)

**Comment by lynnntropy** [comment]
o/ I'll take care of this.

**Comment by papistan** [comment]
Great additions by @omegavesko . Still need many more - thanks all
