### ISSUE TITLE
Add Front End Dev-focused questions and answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#106]
Check out the decks of Q&A cards [here ](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) . What are we missing? 

Create a new deck and add questions and answers that might test core Front End concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Fill in here ](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) and submit pull request.

[Example of question types / length](https://github.com/khan4019/front-end-Interview-Questions#html-basic-questions-for-begginers)

**Comment by amberasaurus** [comment]
I added some questions for https://github.com/papistan/FrontEndTrivia/pull/115
Please feel free to remove any you think don't fit what you were looking for.
I also used the W3C logo for the image for the deck, but also feel free to change that if desired.
Thanks!

**Comment by papistan** [comment]
I have merged in @Maowse 's new deck of general front end related questions. If others think of additional ones or new decks we need, feel free to make a pr. Thanks
