### ISSUE TITLE
HTML questions / answers (20-30)

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#11]
Add questions and answers that might test core HTML concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

[Example of question types / length](https://github.com/khan4019/front-end-Interview-Questions#html-basic-questions-for-begginers)

**Comment by harshcrop** [comment]
I can work on this

**Comment by rishabh-bansal** [comment]
@harshcrop  I'm already working on this, submitted a pull request. Hope you understand. :) #15

**Comment by papistan** [comment]
@harshcrop @rishabh-bansal  we can use many more html questions and answers! Also can create separate deck if there are other html topics to focus questions on. thanks!

**Comment by rishabh-bansal** [comment]
@papistan will update you as soon as I get more questions

**Comment by 278kunal** [comment]
Looking forward to work on this ?

**Comment by papistan** [comment]
@278kunal sorry for delayed response. Yes please. Thanks!
