### ISSUE TITLE
Add basic jQuery questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#114]
Add a new questions / answers to deck labeled 'jQuery: Basics' - that might test core jQuery concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Add to deck here ](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) and submit pull request.

[Example of question types / length](https://github.com/khan4019/front-end-Interview-Questions#html-basic-questions-for-begginers)

**Comment by coymeetsworld** [comment]
I can take a look at this.
