### ISSUE TITLE
CSS questions / answers (20-30)

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#12]
Add questions and answers that might test core concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

[Example of question types / length](https://github.com/khan4019/front-end-Interview-Questions#html-basic-questions-for-begginers)

**Comment by rishabh-bansal** [comment]
I want to work on this :) #18

**Comment by sabarnac** [comment]
Added a pull request :) #16

**Comment by itaditya** [comment]
Hey can I work on this

**Comment by papistan** [comment]
@itaditya yes, please! We need many more questions / answers. Also, can create new decks, such as flexbox, etc. Will add some issues. Thanks

**Comment by 278kunal** [comment]
Hey @papistan I would love to work on this. As Hacktoberfest kicks off on 1st October, should I start making contributions from 1st October only ?

**Comment by papistan** [comment]
@278kunal great! Honestly not totally sure how Hacktoberfest counts date (PR versus commit date). I will wait to merge after October 1, either way. More questions are very much needed. Thanks
