### ISSUE TITLE
Upgrade project dependencies

### ISSUE THREAD

**Issue by jaimellamasi** [papistan/FrontEndTrivia#120]
* **I'm submitting a ... **
  - [x] bug report

* **What is the current behavior?**
`webpack -p` doesn't compile

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Having
`node -v` => v8.6.0
`npm -v` => 5.3.0
1. Clone the repository.
2. Run `npm install`

ERROR in ./src/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/_username_"

* **What is the expected behavior?**
Compiling the project correctly

Is somebody else experiencing this error?

**Comment by papistan** [comment]
@jllamasi weird. I just tried to pull down the repo and didn't have that issue. You may need to install babel-preset-es2015, try: 

 ` npm install babel-cli babel-preset-es2015 `

source: https://stackoverflow.com/questions/34819473/error-couldnt-find-preset-es2015-relative-to-directory-users-username

**Comment by jaimellamasi** [comment]
@papistan quite weird. I just cloned from another laptop my forked repository, also yours, and still getting this error. I tried the command you attach but it didn't work. I'll keep trying...

**Comment by jaimellamasi** [comment]
It worked adding a .babelrc file with presets config:

`{
    "presets": [
        "es2015",
        "react"
    ]
}`
