### ISSUE TITLE
Create a list of all current decks

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#123]
Check out the decks of Q&A cards [here ](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) .  
We need a commented out list of all deck titles at the top (for ease of finding them until we can refactor design.) 

Add the following: 
1. commented out list of all deck titles at top of file - [Fill in here ](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) 
2. Add list of current decks to readme under new section

**Comment by srhrshr** [comment]
Please check if [this](https://github.com/papistan/FrontEndTrivia/pull/124) works.
