### ISSUE TITLE
Add new ‘Bootstrap: Basics’ deck with questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#127]
Add a new deck, image and questions and answers related to core bootstrap concepts [here ](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) .  

Please add an open source and optimized image under styles/images, also. Finally update the deck list at top of file and also readme.

**Comment by harshcrop** [comment]
pull is coming
