### ISSUE TITLE
Add new deck ‘LESS: Basics’ with questions and answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#128]
Add a new deck, image and questions and answers related to core LESS concepts [here ](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) .  

Please add an open source and optimized image under styles/images, also. Finally update the deck list at top of file and also readme.

**Comment by harshcrop** [comment]
check pull request

**Comment by papistan** [comment]
@harshcrop just asked for your refactor and then I'll merge this. thanks!
