### ISSUE TITLE
Add new ‘Git’ deck with questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#130]
Add a new deck titled “Git”, image and questions and answers related to good git workflow, including common best practices, commands, etc [here](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) 

Potential resources list here: https://help.github.com/articles/git-and-github-learning-resources/

Please add an open source and optimized image under styles/images, also. Finally update the deck list at top of file and also readme.

**Comment by cmd-kvn** [comment]
@papistan I'd like to help!
