### ISSUE TITLE
Add Git workflow trivia questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#133]
Add questions to deck titled “Git” related to good git workflow, including common best practices, commands, etc [here](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) 

Potential resources list here: https://help.github.com/articles/git-and-github-learning-resources/

**Comment by kushalpandya** [comment]
I can add a couple. :slightly_smiling_face:

**Comment by rchioreanu** [comment]
I'll also add some.

**Comment by urianchang** [comment]
I added a few questions in regards to managing commits.
