### ISSUE TITLE
Scope out basic structure for API backend

### ISSUE THREAD

**Issue by urianchang** [papistan/FrontEndTrivia#138]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Feature request: Need to scope out a basic structure for API backend that the frontend can use. It should also be relatively easy to work with so others can contribute to it.

* **What is the motivation / use case for changing the behavior?**
Currently, the questions are statically served. There isn't an API that the frontend queries for questions. Additionally, to make the app more robust (e.g. user info), some type of database will be needed.

**Comment by urianchang** [comment]
@papistan As mentioned in #14 , please assign this ticket to me. Thanks!

**Comment by papistan** [comment]
@urianchang sorry for delay. Thanks very much for this issue and your pr. I’ve actually just been at GitHub Universe conference for last two days and fleeing ash-filled Bay Area tomorrow. . Will work on this tomorrow after travel. Feel free to keep adding anything else you’d like and submit PRs. Thanks again

**Comment by urianchang** [comment]
@papistan Cool! I wanted to go to GitHub Universe, but tickets were a bit pricier than I could afford at the moment. How was it? 

Anyways, I finished up with creating a really basic backend API with MongoDB database. Please let me know what you think. Thanks!
