### ISSUE TITLE
Add new 'Javascript: ES8' deck

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#141]
Add a new deck, image and questions and answers related to new developments within Javascript ES8 [here ](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) .  

Potential resource for questions [here](https://hackernoon.com/es8-was-released-and-here-are-its-main-new-features-ee9c394adf66)

**Comment by wocoburguesa** [comment]
Mind if I work on this one, @papistan?

**Comment by papistan** [comment]
@wocoburguesa sure. thanks!

**Comment by wocoburguesa** [comment]
Created a PR. @papistan PTAL.
