### ISSUE TITLE
Add, Edit or Update Front End Related Questions for FrontEndTrivia.com - JS, CSS, HTML, React, Git

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#153]
Help us to Add, Edit or Update questions and answers related to the main issues a new Front End Developer should know / consider -  [here ](https://github.com/papistan/FrontEndTrivia/blob/master/src/data/file.js) - submit pull request.

**Comment by rajputvishwas** [comment]
are you looking for questions and answers in specific format?
