### ISSUE TITLE
No ReactJS questions

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#24]
Add questions and answers that might test core React concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

[Example of question types / length](https://github.com/khan4019/front-end-Interview-Questions#html-basic-questions-for-begginers)

**Comment by rishabh-bansal** [comment]
Will be working on this
