### ISSUE TITLE
Don't add node_modules to your git repository

### ISSUE THREAD

**Issue by codepunkt** [papistan/FrontEndTrivia#25]
Happy to help. `Hacktoberfest` tag would be appreciated! :)

**Comment by jaimellamasi** [comment]
neither bundle.js?

**Comment by papistan** [comment]
@codepunkt @jllamasi Thanks for this. I'm new to node, so happy to take your advice on what to cut. Can I still push git repo up to heroku after removing without issues deploying? If so, feel free to make PR with changes.

**Comment by romellogoodman** [comment]
@papistan yes! When you push to heroku it redownloads the node_modules and will deploy the same as before.

Created a PR to fix this

**Comment by papistan** [comment]
@romellogood thanks! Will wait to merge Oct 1st for 'hacktoberfest' credits.
