### ISSUE TITLE
Add Flexbox questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#27]
Create a new deck titled 'CSS3 Flexbox' - and add questions and answers that might test core concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

[Example of question types / length](https://github.com/khan4019/front-end-Interview-Questions#html-basic-questions-for-begginers)

**Comment by gcasalett** [comment]
I'd love to get this going!

**Comment by papistan** [comment]
@gcasalett awesome - that would be great, thanks!
