### ISSUE TITLE
Add ES6 questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#28]
Create a new deck titled 'Javascript: ES6' - and add questions and answers that might test core concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

This deck should test concepts focused on features of ES6, for example: 
- Default Parameters 
- Template Literals
- Multi-line Strings
- Destructuring Assignment
- Enhanced Object Literals
- Arrow Functions
- Promises
- Block-Scoped Constructs Let and Const
- Classes
- Modules

[Example of question types / length](https://github.com/khan4019/front-end-Interview-Questions#html-basic-questions-for-begginers)

**Comment by P-WM** [comment]
May I take this as a Hacktoberfest treat?

**Comment by papistan** [comment]
@P-WM for sure. We need lots of questions, so others can contribute as well. Thanks

**Comment by P-WM** [comment]
👍

**Comment by AkshayIyer12** [comment]
Can I contribute to this for Hacktoberfest?

**Comment by papistan** [comment]
@AkshayIyer12 yes, thanks!

**Comment by P-WM** [comment]
I've left a Pull Request with some questions in to get started. I didn't want to go wild in case the style wasn't want you were looking for. In particular, I've used a code snippet, which was not a great move as it looks a little confusing on the card.

**Comment by nveenjain** [comment]
Can i contribute on this?

**Comment by papistan** [comment]
@nveenjain yes, please do. Thanks

@P-WM thanks, will take a look and hopefully merge tomorrow. The code snippet is unfortunately a problem for now - though I’ve got to spend some time to figure out how to fix. I don’t want the cards full of code (as this is more for quick overarching concepts) but we at least should be able to show a function or two for reference. Leave in for now and we’ll get a fix for it later. Thanks!

**Comment by P-WM** [comment]
@papistan Perfect. I'll leave it for the moment then. It's just a for loop with one statement to ask a question re: let/var. Nothing major.

Also, there wasn't an ES6 deck when I started, so I made one using the JS logo.
