### ISSUE TITLE
Add Intermediate-level JavaScript questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#29]
Create a new deck titled 'Javascript: Intermediate' - and add questions and answers (no limit on # really) that might test mid-level concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

Some potential references: 
- http://www.thatjsdude.com/interview/js2.html
- https://github.com/khan4019/front-end-Interview-Questions#javascript-for-intermediate-level-developer

**Comment by Rishabh-Kumar-Bothra** [comment]
@papistan shall i work on this?

**Comment by papistan** [comment]
@geekychaser yes please. We need a lot of questions so several may work on it. Thanks!

**Comment by cmd-kvn** [comment]
@papistan I hope you don't mind, I contributed to this. [PR 41](https://github.com/papistan/FrontEndTrivia/pull/41)

**Comment by nmkettler** [comment]
@papistan I just sent a pull request. I added a code snippet as a binding example but was unsure the exact styling you would like on it or if at all. Let me know and I can revert any changes. 

Thanks!

**Comment by papistan** [comment]
@cmd-kvn @nmkettler thanks, both! I'll review today. Feel free to add more after, if you'd like.
