### ISSUE TITLE
Add DOM questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#30]
Create a new deck titled 'Javascript: DOM' - and add questions and answers (no limit on # really) that might test DOM manipulation-related concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

Some potential references for inspiration: 
- http://www.thatjsdude.com/interview/dom.html

**Comment by geekychaser** [comment]
@papistan  i will be working on this.

**Comment by Rishabh-Kumar-Bothra** [comment]
@papistan shall i work on this?

**Comment by papistan** [comment]
@geekychaser yes thanks!
