### ISSUE TITLE
Add more JavaScript commonly-used built-in methods

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#53]
Add additional commonly used built in methods to deck titled 'Javascript: Common built-in methods' - and add questions and answers (no limit on # really) [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

For reference (though some may exist already so please check, thanks):  from https://www.xul.fr/javascript/cheat-sheet.php

String methods

charAt() character at the given position
charCodeAt() code of a character
concat() concatenate with the argument
indexOf() position of a character
lastIndexOf() position from the end
localeCompare() localized comparison
matchapply a regular expression()
replace() replace a substring
search() search a substring
slice() extract a part
split() cut to build an array with parts
substring() extract a part
toLowerCase() convert to lowercase
toUpperCase() convert to uppercase
toLocaleLowerCase() localized lowercase
toLocaleUpperCaselocalized uppercase ()

Array, index and methods

a["one"]=1 assignment by indice
a.one=1 assignment by attribute
delete a["one"] deletion by indice
delete a.one deletion by attribute
for(var k in a) {} iteration on the content
concat() add a second array
join() concatenate the elements into a string
push() add an element
pop() get and remove the last element
reverse() invert the order of elements
shift() insert an element at start
slice() extract a sub-array
spliceinsert an array ()
sort() sort the elements
toString() return the array as a string
unshift() get and remove the first element

**Comment by tomyfalgui** [comment]
will work on this!

**Comment by pari08tosh** [comment]
Hi! I would like to work on this as my first contribution :)

**Comment by sagarvd01** [comment]
Hi @papistan made a PR #69

**Comment by pari08tosh** [comment]
#70
