### ISSUE TITLE
Add new deck 'Javascript: Common event handlers'

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#54]
Add new deck  'Javascript: Common event handlers' - and add questions and answers (no limit on # really) [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

For example:  from https://www.xul.fr/javascript/cheat-sheet.php

onAbort loading stopped
onBlur focus lost
onChange content modified
onClick clicked
onDblClick clicked twice
onDragDrop moved
onErrornot loaded
onFocus focus entered
onKeyDown key depressed
onKeyPress key pressed
onKeyUp key released
onLoad just after loading
onMouseDown mouse button depressed
onMouseMove mouse moved
onMouseOut mouse exited
onMouseOver mouse on the element
onMouseUp mouse button released
onReset reset form button clicked
onResize size of page changed
onSelect element selected
onSubmit submit form button clicked
onUnload

**Comment by mankutila** [comment]
I'll help with this one)

**Comment by papistan** [comment]
@mankutila thanks for great additions. If anyone else can add more that would be great.
