### ISSUE TITLE
Add new deck 'CSS: Animations' 

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#55]
Create new deck titled 'CSS: Animations' - and add questions and answers (no limit on # really) [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

For reference, concepts found here: https://css-tricks.com/almanac/properties/a/animation/

**Comment by alfredlucero** [comment]
First time doing this for Hacktoberfest but submitted a PR for this 😄
