### ISSUE TITLE
Add new deck titled 'CSS: Pseudo-classes'

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#56]
Create new deck titled 'CSS: Pseudo-classes' - and add questions and answers (no limit on # really) [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

For reference, concepts found here: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

**Comment by alfredlucero** [comment]
Added some QA for the deck in a PR 🌮
