### ISSUE TITLE
Add new deck titled 'SASS: Basics'

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#57]
Create new deck titled 'SASS: Basics' - and add questions and answers (no limit on # really) [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

For reference, concepts found here: http://sass-lang.com/guide  or some other good question and answer format for basics

**Comment by outofgamut** [comment]
I can pick this one up

**Comment by papistan** [comment]
@outofgamut thanks! there is a new deck added so please update your branch and add directly to that deck
