### ISSUE TITLE
Add new deck titled 'Javascript: Design Patterns' 

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#58]
Create new deck titled 'Javascript: Design Patterns' - and add questions and answers (1-2 sentences max) that help to introduce basic concepts of different design patterns (no limit on # really) [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

This is difficult to boil down into flash cards, but at least some basic info would be good.
One reference to use may be (though very long):
[Learning JavaScript Design Patterns](https://addyosmani.com/resources/essentialjsdesignpatterns/book/#decoratorpatternjavascript)

**Comment by tygas** [comment]
Will add this one

**Comment by papistan** [comment]
@tygas thanks, that would be great!
