### ISSUE TITLE
Add new deck 'Webpack: Basics' with questions and answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#59]
What are the basic concepts of Webpack a developer should know? Can you boil these down into digestible 1-2 sentence questions and answers?

Add new deck titled 'Webpack: Basics' - and add, image to images folder, questions and answers (no limit on # really) [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

Potential resource [here](https://hackernoon.com/webpack-the-basics-2712a7ad640b)

**Comment by harshcrop** [comment]
hey, i am working on this.

**Comment by harshcrop** [comment]
add new pull check out that.

**Comment by papistan** [comment]
@harshcrop thanks!   We still need many more if others want to contribute
