### ISSUE TITLE
Need suggestions for improvement

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#60]
Check out progress so far: https://frontendtrivia.herokuapp.com/

Besides issues listed currently, what else do you think would make this useful for a new front end developer preparing for interviews and exposing themselves to new / core concepts? Please list in comments below. 

Also, what good forums do you know of to reach front end developers? 

Thanks!

**Comment by nutmegprince** [comment]
Hi there, this is just a cosmetic issue, but the first thing I noticed when I opened the link to check out the progress was that the text (HTML, JS, CSS) on the image is almost impossible to read against the background. This would be an easy fix (add a bit of white glow or change font color) and it would really make the home page easier to understand.

**Comment by Gangezilla** [comment]
Hi, it might be useful to try and enforce some styling rules, possibly by having some sort of ESLint configuration.

Maybe also a pull request template, with some of the things that people putting up PRs should do beforehand, such as running tests, or compiling for production or something like that. I can help with this if you want 👍

**Comment by Gangezilla** [comment]
Thinking about it a bit more, it might be worthwhile to flesh out the backend a bit more, it'll definitely be easier to integrate a user login system that way. Also, the reducers isn't really an appropriate spot to leave all the questions, maybe it would be worth considering pulling them out into a separate JSON file to clean up the codebase a bit.

**Comment by papistan** [comment]
@Gangezilla great suggestions. I will submit an issue and great if you could help with those - especially the json file (as I agree the reducer is not a long term solution) 
@nutmegprince thanks for suggestions. That is stock photo so needs replacing. If you have any suggestions for new front-page photo that would be great. Thanks!
