### ISSUE TITLE
Update Contributing.md

### ISSUE THREAD

**Issue by nveenjain** [papistan/FrontEndTrivia#72]
In contributing.md, under enforcement section, there is requirement to put team's email address. I would have implemented that in my next PR(JS questions), but that would require mail id that is to be added there.
Also list of contributors can be updated ;)

**Comment by papistan** [comment]
@nveenjain thanks, can you help with updating this?

**Comment by nveenjain** [comment]
@papistan I would love to, but this requires a team email address too, what should I put there?

**Comment by papistan** [comment]
Sorry - can you just put mine for now? jpapisan@gmail.com  Thanks!

**Comment by nveenjain** [comment]
@papistan, I submitted a PR #140. Please look into it. thanks :)
