### ISSUE TITLE
'SASS: Basics' deck needs more questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#76]
Add to deck titled 'SASS: Basics' with additional questions and answers (no limit on # really) [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

For reference, concepts found here: http://sass-lang.com/guide  or some other good question and answer format for basics

**Comment by Gangezilla** [comment]
Have added a few in this PR https://github.com/papistan/FrontEndTrivia/pull/85 :)
