### ISSUE TITLE
Add to 'CSS: Pseudo-classes' deck with questions / answers

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#77]
Add questions to deck titled 'CSS: Pseudo-classes'  (no limit on # really) [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

For reference, concepts found here: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

**Comment by harshcrop** [comment]
I start working on it.

**Comment by harshcrop** [comment]
@papistan I push 2 pull you merge it but in Hacktoberfest show me only one pull?

**Comment by yuschick** [comment]
PR incoming.

**Comment by maridilip** [comment]
Hi i have raised my first pull request and kindly review.
