### ISSUE TITLE
Add questions / answers to 'Javascript: Foundations' deck 

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#80]
Add questions / answers to 'Javascript: Foundations' deck - (no limit on # really) that might test core concepts and mimic questions that might be asked in phone screens. Should be concise enough to fit into 1-2 sentences. [Fill in here](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) and submit pull request.

Some potential references: 
- https://h5bp.github.io/Front-end-Developer-Interview-Questions/#js-questions
- concepts from [David Shariff](http://davidshariff.com/blog/preparing-for-a-front-end-web-development-interview-in-2017/):
Execution context, especially lexical scope and closures.
Hoisting, function & block scoping and function expressions & declarations.
Binding – specifically call, bind, apply and lexical this.
Object prototypes, constructors and mixins.
Composition and high order functions.
Event delegation and bubbling.
Type Coercion using typeof, instanceof and Object.prototype.toString.
Handling asynchronous calls with callbacks, promises, await and async.
When to use function declarations and expressions.

**Comment by tygas** [comment]
Can take this one too, but I see there is more than 20 questions, @papistan  you want more?
