### ISSUE TITLE
Move deck objects from reducer to alternative (json?) file

### ISSUE THREAD

**Issue by papistan** [papistan/FrontEndTrivia#95]
As suggested by @Gangezilla , all deck objects are currently held in [this reducer](https://github.com/papistan/FrontEndTrivia/blob/master/src/reducers/reducer_decks.js) , which is not ideal. Would be great to have someone move to a json file or alternative. Please test and submit pr, thanks

**Comment by Jpfonseca** [comment]
@papistan  can you assign me to the task ??

**Comment by papistan** [comment]
@Jpfonseca sure, please. thanks!
